name: Ruff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff format check
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check .

      - name: Run Ruff lint check
        uses: astral-sh/ruff-action@v3
        with:
          args: check .
